apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure/csi-driver-nfs.yaml
  - workloads/jellyfin.yaml
  - workloads/sonarr.yaml
  - workloads/radarr.yaml
  - workloads/seerr.yaml
  - workloads/prowlarr.yaml
  - workloads/flaresolverr.yaml
  - workloads/qbittorrent-secrets.yaml
  - workloads/qbittorrent.yaml
  - workloads/newt-infra.yaml
  - workloads/newt-secrets.yaml
  - workloads/newt.yaml
  - workloads/website.yaml
  - workloads/stalwart.yaml
