apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure/csi-driver-nfs.yaml
  - workloads/jellyfin.yaml
  - workloads/newt-infra.yaml
  - workloads/newt-secrets.yaml
  - workloads/newt.yaml
