apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure/csi-driver-nfs.yaml
  - workloads/storage.yaml
  - workloads/media.yaml
  - workloads/newt.yaml
  - workloads/tools.yaml
  - workloads/website.yaml
  - workloads/wireguard.yaml
