apiVersion: v1
kind: Secret
metadata:
    name: netbox-db-secret
    namespace: netbox
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Hrh3z0+X3V+ZNb6SFVD9JAi/bqtSZIZYItlXb0adk4SJGSuXGfl5S6HH,iv:9rFDCxyxck1x1nSgHlJWmLDLz5Cf7ACJH+MiT2jvAOQ=,tag:gJNLjzU/yzrDqBFmONReog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WlA5bER6ckJMSTJpWUV3
            UE1kdy96bkZNL3JUejd1cHZVc0NVWlByQ0E4ClptVHdWTEFkMHc3LzZBK2o0ZXV3
            aHh6L0UwaE4vb3BYNnA3MGRrSWFpMkkKLS0tIEN1RlNnQ05kUHd0M0Q2MUZ5R2cz
            N3BaU3lpWTZWcmkyemlNTXYwVzlzLzQKNc7GT1fpq4i5ZdwUtZdr/YWmxA82yv1u
            Zxj3zWyC/WNXSRAysGC+py1ATFWVC4zPL7d4aiurIWcxvdkX/gQuuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ygm9sy4ww2l95wwpta72g9se7lev3mqp9d898zxzs9a36yx9gsmqsvl3t3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T05:57:43Z"
    mac: ENC[AES256_GCM,data:+zkogMFfFFu1eV1CjYWQMVBeXgrYAMaEBPyyQ5EbZ85N6VuewTz4JDu8ZO4hpiywPOfqaJfshtdmUYELswF+975fAxXEYS6nYzPIH7m+c44WqwKyp9V214P+kqfT3EV43YAz/YPmLdKOq31K2bNRMlh3lDLIcp5TLJorM5gTYgs=,iv:eWH4ZRu4eq1+zaQVQjpac40+ewh03RPyt97Z80CqRU4=,tag:NaQd0PuYKE6KiGX2lnAgTw==,type:str]
    version: 3.13.1
