apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: metallb
      namespace: flux-system
  chart:
    spec:
      chart: traefik
      version: "34.x.x" # Uses latest v34 series
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    deployment:
      kind: DaemonSet
    ingressRoute:
      dashboard:
        enabled: false
    ports:
      web:
        port: 80
      websecure:
        port: 443
    service:
      type: LoadBalancer
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
