apiVersion: apps/v1
kind: Deployment
metadata:
  name: omni
  namespace: omni-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: omni
  template:
    metadata:
      labels:
        app: omni
    spec:
      containers:
        - name: omni
          image: ghcr.io/siderolabs/omni:latest
          args:
            - "--config-path=/etc/omni/config/omni.yaml"
            - "--config-path=/etc/omni/auth/omni-auth.yaml"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_ADMIN
          ports:
            - name: omni
              containerPort: 8080
              protocol: TCP
            - name: siderolink-api
              containerPort: 8090
              protocol: TCP
            - name: k8s-proxy
              containerPort: 8095
              protocol: TCP
            - name: wireguard
              containerPort: 50180
              protocol: UDP
          readinessProbe:
            httpGet:
              path: /healthz
              port: omni
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: omni
              scheme: HTTP
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /data
            - name: keys
              mountPath: /etc/omni/keys
              readOnly: true
            - name: config
              mountPath: /etc/omni/config
              readOnly: true
            - name: auth
              mountPath: /etc/omni/auth
              readOnly: true
            - name: dev-tun
              mountPath: /dev/net/tun
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: omni-data
        - name: keys
          secret:
            secretName: omni-keys
        - name: config
          configMap:
            name: omni-config
        - name: auth
          secret:
            secretName: omni-auth
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
