apiVersion: v1
kind: Secret
metadata:
    name: omni-auth
    namespace: omni-system
stringData:
    omni-auth.yaml: ENC[AES256_GCM,data:jSE4RO8YYU+Wa/hhBDFXbqKIMXLeyHVMZyrTA9puUgJvPj0+J1n9xHEcxmR2KkpW6wCo/km55j7Zl+OL6Tz5uT5g8+U7htIHIsfOoYMumjpzQ4VJLRzAPd5VZZjc48g019961uZ+PBC3knQPL3t1VBW1yc1rogSRGJYB5Q3ITJa7Zu4Y50oY416Ix14j45fDU1aCIIvub9sAHsc4+msoD12LRhrm5RkPNlSdzyErNLEVPbbv1dQIwEzDiw519VwW1c7AEpRtNb9WHabhK/86EC4CW5tUw7udOHMuZHcHbK7+Gq/WRXTbusSx2aHeXLlnx/CEn7xnj3gx6TSxAyWoCKqIZa+N8tnNkl5ZjcnmhZFx0hFMU1x/+nAHZWbmm0ST8tsSIcdddlxb6ygQb6l+kOtr,iv:QHfk5Vwg7vPZT6Rv0n2YnnBwhh9gIPBJsbUkzH+bbmc=,tag:i9j4+lUOmE+GIenF2IGMcg==,type:str]
sops:
    age:
        - recipient: age1v9l673n53dy5dl4ucecuk6val9lqulq2nkvsmj5gjxumf8sjh5hsgjj09h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaFMxVkwzd09hd0lWcisv
            UTltcFJRT0MzaFREZ3lGdEZJTCs5VlFIQzNBCmdCb0ExbkdDdzliVk1KN0VqVkt4
            M2R0eVFRN3Y0eFNwc1VwUXBmUmJ4akEKLS0tIHVLUWtQNnpwNngzeGpvZEFnTm5T
            dlJmRXVoZHFsR2Y4dXBmSlV1UWE1YkEKHN5zAvDqubioTWewQH5Oj8u9jPtboq9j
            bG7Z/Mepw2f2mt27nHV6lZ9lHRUxv181bT9ZLj3cWOPgqchRHwQGyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T04:13:08Z"
    mac: ENC[AES256_GCM,data:x8suARBr70E3VY/TlTrs2tYgaammemWFk93TPdSsESUia6j9BnSivgnPqGS+vbDJjjugIy1Qjc0aAfDrqKdhVGtah8fw2HZFKk7JieU5AW8DbOeHKB2nLbAdOWpOzQF+VghplTB/DHm2uMCImItAGTwp9xqlVdzQTvuAJ/y5cVg=,iv:yHKodPLMQId4zFWWDr7CLB3FZoq54UQEPEGEXg8MlSo=,tag:c2CKC6Teh9lyKRjDdBSE2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
