apiVersion: v1
kind: Secret
metadata:
    name: wireguard-config
    namespace: wireguard
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:1j1coYxpMzPz4KvWmostUk8tvpjD+y00DEbtiJwNawPAIeiWUe9jjRQJkBo5pW7GtBpr7zwmYT3TyUbKpcwMX27jfLd/paCXEnuXClc/bBymxlSBysAFvcPZJOCtIsoihkeaamnTIB5orANatDL4sIXBzCYCc8/+RU7hkAtcvEpjGNrLzGNz5aqCLtEngSPJdqMwbkL35L6VZBdjprXNnt4q4uy+aMD3/TyBNftKHEoXWGefL9UigiRUxlw3/mS7uUGqEhyh84DuXvBXD/b7uLM++Lx9HtFckJDxmNI407ytrbXhdLOkre3QnZfZalEyjJgCELydCUU4HtWqyBsWpdq7dpXv7+shcF9X6dFQHRsspaM3d1nHjNnOnkRIgrlXNA/9novpNM1TyO6/swKzO4MBgd8jb6Gdy2pifq3s0ROvaTtAgmU5HeKjzHbIEYsCS7f6B6RZ/7bPWSzveeQasc2P87qOv4Kw8uglu22+jm6gekzmCsPoZWnxqZEDF75QHSJpaqKF2CqkJOD5f4y0/BLGh6J/Xy3oFjtgh/VvNANjuZEKnpSH46pah+qkZOURC4kYNv53BYE/q/+qq/dgIpch6mpPKCxaqjX6N29GXOMHPsJjD77fXGXB1w==,iv:h76LhEUyJLZP2xtUpwm+XsFznUMUeLjLSfH5+Lp/K+I=,tag:F5DInqFZOvhnSDTo8DJ8SQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaW5OQkl4RjZHa1BVNy9X
            M1phdnA0akNFUjBmTmlmQ0c3andHT0F1dlRvCk1SN2tzUUhqclV6eWd0dTNBcGcr
            N0dXczFiUjgyZURhdUUwV3pJYmNtZ0UKLS0tIHZQMk1PWGV5TW82K0QveFp3MUxx
            OHd4N0dKMnM4ekhtamJtUm54cjFSTkUK+g7zBHckDNs0Es/nc4JRB34N0bT1ikDq
            djzoiA199aaJxeuasso7Cz8CEHyVjcYDzbtz583nB+kCTu+TYrRPZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ygm9sy4ww2l95wwpta72g9se7lev3mqp9d898zxzs9a36yx9gsmqsvl3t3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T18:36:23Z"
    mac: ENC[AES256_GCM,data:HfHP6xyaXmcsAQ0iwT8hQWKKshcElx9h2PKCrBFnL23gxBnAnTZzK5/6pUd/zwmZc2KDSt1rR6NSk2lnx0iw2Q4O9tp/K/7B8GoNV+zVVVT1KRCGf9pKCQ5BjhUzW8Z+DuverBR/pjeobTr2hDtRQCbaMXZ/SQrNw5+fhXtBE6c=,iv:cz0m33btmk5O4TtNEj7GUkcT7XHphjT+9HK7hC1f5BQ=,tag:1AmfTdBMn7FUcqubKyo71w==,type:str]
    version: 3.13.2
