apiVersion: v1
kind: Secret
metadata:
    name: pangolin-routes-secret
    namespace: pangolin
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:Vb0k5uIdIGnESCmqo68PBjIoVIbZ1bcEUj2tZcY=,iv:h1gdMTq6P5BrrhLxEAatsbt5H5ifV78vuRfOTImBdbI=,tag:pHJSif9ioe6Quuikx4+orA==,type:str]
    PANGOLIN_ORG_ID: ENC[AES256_GCM,data:qrvQsgjP0ZI=,iv:4xskzladgN/4eKYpF2BTGibmrY5JGAOBk+TzlcTauH8=,tag:QT0tqdeK3jOqkcImfeSGfw==,type:str]
    PANGOLIN_API_KEY: ENC[AES256_GCM,data:O5tD2yQWI/JnyyWig6Erg8v7HYcZuIg6o+KGkRE8rZ8Qn5uchdg4tO+m9q3yVNzB9Kp4oNGCwkI=,iv:jkGrdqLsBu25Kfde55auBAyyJgX5jg0AxxDVjAostBw=,tag:rKntIQFTcTuzHujANDXamQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByL0FlbW44aEJZTU4wNTdk
            aVhpbCswUGRSbFd2UHhOeVNTblZ2cWZlRHdFCnlmWkdNN04wVGJQdjdUdDN5bWpy
            S0g2YnpUeVM2ejNJejNBMWRoZFFpN2cKLS0tIDN2OWR0ZHdtVXNjbllBSGh2cmxO
            aEpqQ05LNG9PYmVNbnQxTG5MdytBTk0K+1cBPBMIEA/Y1/cE4H2XEwEXuHYMagXw
            pvXg2n1kT5sbVR18SBmCUJCBDwrMEqRR8/fubWcTIL4GhuXyeig1mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ygm9sy4ww2l95wwpta72g9se7lev3mqp9d898zxzs9a36yx9gsmqsvl3t3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T02:22:30Z"
    mac: ENC[AES256_GCM,data:BtAJyYN687Uul2bx0ZwIHEYnenk7adn8rlZBPzNbMp3hcfY7worgg2GlHmY/5nAsT5QYzhRMbKJZEv+sn6kjd6/WNdAP3IRACkS0Oupzul39uEZBsqxskOVAPUWVnvRjpNTjUJ3Z04vDI+gmv9MservkE8rXqKMXpByOeQYO3PY=,iv:AFqfohWo3Jd5KTDcSr0VC3yrMr0LaSXXXal4ZEAUgb0=,tag:Gv79c38d4XjZoPgmeqEmPg==,type:str]
    version: 3.13.1
