apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.fossorial.io
    chart: newt
    targetRevision: 1.5.0
    helm:
      releaseName: newt
      valuesObject:
        newtInstances:
          - name: main-tunnel
            enabled: true
            acceptClients: true
            auth:
              existingSecretName: newt-main-tunnel-auth
            nativeMode:
              enabled: true
            configPersistence:
              enabled: true
              type: persistentVolumeClaim
              existingClaim: newt-config-pvc
              mountPath: /.config/newt-client
            generateAndSaveKeyTo: /.config/newt-client/private.key
  destination:
    server: https://kubernetes.default.svc
    namespace: newt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
