apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newt
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/cnbrown04/homelab.git
      targetRevision: HEAD
      path: sisyphus/workloads/newt
    - repoURL: https://github.com/cnbrown04/homelab.git
      targetRevision: HEAD
      path: sisyphus/workloads/newt/secrets
      plugin:
        name: sops-decrypt
    - repoURL: https://charts.fossorial.io
      chart: newt
      targetRevision: 1.13.0
      helm:
        releaseName: newt
        valuesObject:
          newtInstances:
            - name: main-tunnel
              enabled: true
              acceptClients: true
              auth:
                existingSecretName: newt-main-tunnel-auth
              nativeMode:
                enabled: true
              configPersistence:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: newt-config-pvc
                mountPath: /.config/newt-client
              generateAndSaveKeyTo: /.config/newt-client/private.key
              blueprintFile: /etc/newt/blueprint.yaml
              blueprintData: |
                public-resources:
                  jellyfin:
                    name: "Jellyfin"
                    mode: http
                    full-domain: jellyfin.calebbrown.dev
                    targets:
                      - hostname: jellyfin.jellyfin.svc.cluster.local
                        port: 8096
                        method: http
                        enabled: true
                  argocd:
                    name: "ArgoCD"
                    mode: http
                    full-domain: argocd.calebbrown.dev
                    targets:
                      - hostname: argocd-server.argocd.svc.cluster.local
                        port: 80
                        method: http
                        enabled: true
                  sonarr:
                    name: "Sonarr"
                    mode: http
                    full-domain: sonarr.calebbrown.dev
                    targets:
                      - hostname: sonarr.sonarr.svc.cluster.local
                        port: 8989
                        method: http
                        enabled: true
                  radarr:
                    name: "Radarr"
                    mode: http
                    full-domain: radarr.calebbrown.dev
                    targets:
                      - hostname: radarr.radarr.svc.cluster.local
                        port: 7878
                        method: http
                        enabled: true
                  prowlarr:
                    name: "Prowlarr"
                    mode: http
                    full-domain: prowlarr.calebbrown.dev
                    targets:
                      - hostname: prowlarr.prowlarr.svc.cluster.local
                        port: 9696
                        method: http
                        enabled: true
                  seerr:
                    name: "Seerr"
                    mode: http
                    full-domain: seerr.calebbrown.dev
                    targets:
                      - hostname: seerr-seerr-chart.seerr.svc.cluster.local
                        port: 80
                        method: http
                        enabled: true
                  torrent:
                    name: "qBittorrent"
                    mode: http
                    full-domain: torrent.calebbrown.dev
                    targets:
                      - hostname: qbittorrent.qbittorrent.svc.cluster.local
                        port: 8080
                        method: http
                        enabled: true
                  netbox:
                    name: "NetBox"
                    mode: http
                    full-domain: netbox.calebbrown.dev
                    targets:
                      - hostname: netbox.netbox.svc.cluster.local
                        port: 8080
                        method: http
                        enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: newt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
