apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pangolin-routes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/cnbrown04/homelab.git
    targetRevision: HEAD
    path: sisyphus/workloads/pangolin-routes
  destination:
    server: https://kubernetes.default.svc
    namespace: pangolin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
