apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/cnbrown04/homelab.git
      targetRevision: HEAD
      path: sisyphus/workloads/tools
    - repoURL: http://charts.netbox.oss.netboxlabs.com
      chart: netbox
      targetRevision: "8.3.22"
      helm:
        releaseName: netbox
        valuesObject:
          global:
            storageClass: local-path
          externalDatabase:
            existingSecretKey: password
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
