apiVersion: v1
kind: Secret
metadata:
    name: gluetun-secret
    namespace: qbittorrent
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:57bvYhLPRHXQykJlcAq/4pP99CUWvVZBp6fzboXf7GYUWTWUbZ/beP7rdoU=,iv:uZfP4Qo64tCYIQ13D2BJt4oFriOd25i1+IHsFLzoBRg=,tag:RCM391RBxgXWNKIkYH0WAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYTVzUENpNmdpSVRtU3lr
            ZExnb3h6RWdqR1grc3NkUGQvKzloczJzczE0Cjk4RWpxbDJzenZkaFpCSVBkeUJG
            VFlLZnZVSS92SHZ4WERVZ2pnRXV3MzQKLS0tIGV0a3F6MkdYK1l6RnkzcjFvbmcr
            MUVhQ0NOYXdxeGZXQWJydjBVR2F6UnMKbRYv2yOXIxDP+fJ/HMASnFAf73nzkJ5R
            tJXFaptGu1q2uz/5adty9CnfA/VxyPFsY9EHmGkC2ge7EWs6I33JEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ygm9sy4ww2l95wwpta72g9se7lev3mqp9d898zxzs9a36yx9gsmqsvl3t3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T03:34:36Z"
    mac: ENC[AES256_GCM,data:5huX8WPEtVC14iXHgjfPRrOieReCc1T1Yy3E9GRlp0hxUfF4mO/N6MD3umCej3O3Mwqn2MHEaQkK+jWKNcyToiam2T+EGLjeKi5IHR+DdPSDWzFjYWChvLvPLa+4Lyg7PDGJiQL10gfGnHhhnJ16PiwSQLbp6VNPUyhXLedC2Q4=,iv:fzJmFzBL6rCc1XMsK8/g/Fj4xRFvBafb3QnAOJVLkNk=,tag:TMkaHG13NCTIkML5rwdRCQ==,type:str]
    version: 3.13.1
