apiVersion: v1
data:
    NEWT_ID: ENC[AES256_GCM,data:MSqeiZCsR76b+MIwyJRH23ntP7I=,iv:9W1VGtTxZ9OqcDfQP0Kh/5Wh/ZeLZJlcK8u4OjZ3lfI=,tag:zyCh7Sf3k+8nDiL31cvt3w==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:PPq7doYOtvC/+1cg7a0Bit6xIWJnyPBN2C3iEZx7Q3pUFqA/igLXVh5eBIsm8vSub52Y1FGt6V8/FpkpMFpslg==,iv:ZMjM7EShdxZ+R/SZR4sVKmJqFD9G8pZI1c5/Lhh1YT0=,tag:qQzctwdTSO79kr4SynGxzw==,type:str]
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:+HA5MXeeiNBjRtEyIXN8ahxX/O5tc+/DlP+nlj1ZZOFhs/wFjvnjOQ==,iv:7GYpSNjSK7UNqUFowVxvqePJ72e673DnDPKVnNNo7gs=,tag:ebhy63QvLcibXP5Yrp2cZQ==,type:str]
kind: Secret
metadata:
    name: newt-main-tunnel-auth
    namespace: newt
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTT0ZpcXpiWTNNb2FNamVk
            ZkNJSFZqYU1XOFR2a0dzN2drWW9lVHczNjNvClpDZ2N5K0U1bmVIRVpsY2U5RC94
            bHVJZm5vQzNyUE5LZUg2M3VGdytrOXMKLS0tIFU1OFU1eDRnSUw0dnEybnJTNnl4
            SldSRnNpNnpNQzJMQWNuRmdSZXllU3cK6m9N17LQTQi6Wi8whCyY3o2hXQ+/dhRS
            EOk8cQGcu2rbTXtmWQ0By7N0idFHOdFSRu9j+QEqDuV5qz/VTldlEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ygm9sy4ww2l95wwpta72g9se7lev3mqp9d898zxzs9a36yx9gsmqsvl3t3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T02:19:24Z"
    mac: ENC[AES256_GCM,data:Iqn5Pka7Gn9IMlDo3glr/chHopwA5Q4uyasaiQua7zKQbOV4UC/VTlxMh7YYGKx9ONMbvyquGSLRFpynwug6Kg17V+hhslXUfyjAQL4y+Re+Kw9qgXkFL++EA/X6OKJx0HS96zS0bWsW2GrOH4t9+B2v7009NoFGuetKS9kqHGc=,iv:6aRwjzl4zVaUzdmMTYfbg4NKXxcU6ita4CjEczD3v78=,tag:4vqUsXkpB+8cwalfIiLn6w==,type:str]
    version: 3.13.1
