apiVersion: v1
kind: Secret
metadata:
    name: wireguard-config
    namespace: wireguard
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:OFkaPRvlMB0qyyBh3n0vIJVlXwxBCa+yoCqLS+0beUyQ1UfueT/4HF6hGgPwH7RKRceg589zzSBk0fqiQySwbYeO2DZmFs5Eg1nYxbdMcaucauJogZHtj0wAwvpkQ4jsSMAOlSQVA2xILRb6O2MW0SOuxcolxLxMjixlvtQUsCjrMeZCwemJ8OhvI+hZCVEuunEmS+F7eIERhdrBY3TzrLsVhdA/SSeaB0gftZKe55oz/+Pp8tR4GBZaCwic4VcGUFWStVJMpmWHL4y64G+h2gcLvnNuEzYvFqnQdPi6FgTtRyB9Z/4QpkM+hOeMsM6n5b8LuGr4KbWNzuP//3R11Pt9QQWP77xuIn/tMPkDy43K+jF9X0i8Ukg+Jj+NK3E8ilR6mhxS1TtaPSvaSO/WEZo0DuKZxAxg8s1EyXNh0PCCur4b0Mp6BBt0K+uIwq9TodOf4jXBmN0KP31xL7EbGxMxGZrcMVqlr82rWgY0RXxR13YFxRqyXd+ga/Ubbu6lnpojXAraOspJQmGc//3HClO+nxJFC+Yl8kXc+mH8YIOaSVvkHmsBcogU8qzXI2jWBbK+24OefCvLXcclmuNEIVZlNShaKgLTnLL4yTPTwm4crIPAUrqllW6Yi+Gymv7HrnTj0NWFXV/KwXVQEeRTKN2mpNqatxfxlXgeR5GX691ElQSuLDh1V8WMl5Ai4SmkoVnxOOKD7WTZ/UdPLSyqWg==,iv:K5z6q/+h7RlFi6AVx7ykzX/g/9okl+jZuFfIihVhVLU=,tag:yj0oQsdEpsCCD8MzBO0z9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOXliNWw1alY0bU50MXE5
            RzU5U0FVWmN5bC9FdVRVaUlqbjZYc2loV1YwCktRSHNtRmpXbUFkR3FycC93Vmdp
            QnVCWW5sRWJ1WHRTbW8rOVlPRWNmbVEKLS0tIDQ1ekdSb2xRaE5sVDNiYVArc0xz
            NXVmV1F6WDYzNTBvZVAwSXlMMnM1UmsKCazLBQU8zb+RcOOHjciGw7HAqOc7NlOb
            kdihQ6zEYlJX4WfCsFVw7Ei5Y2SxVlQOCgwqeMkZ7RBoX9df7uyUtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ygm9sy4ww2l95wwpta72g9se7lev3mqp9d898zxzs9a36yx9gsmqsvl3t3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T20:52:23Z"
    mac: ENC[AES256_GCM,data:gWMn1HkA70B+eEzs92Sw6GvoXlO+IyqgPIAbz3oPoclcHp8a2IbEHaZW7AnEVBwmRVkfsDHMz/0Y0QQ94USe9BiNCdl+t9CN054Csd6m9+VhSc/THAWJDriGtN+sEy45CznUnfRkzWG3+P3+INFAiI+6EYxJzADQKx4apMbEDEk=,iv:Tv25bQwBgdiojTPnhHk82p0g2+5Xfg+vlTvwNiBtgYc=,tag:0AxvHgmQ+H3tCmGwbl+fwQ==,type:str]
    version: 3.13.2
