apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/ # This ensures flux-system remains managed
  - omni/        # This "activates" the omni folder
  - metallb/
  - traefik/
