apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-audiobooks-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - hard
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: audiobookshelf-audiobooks
    volumeAttributes:
      server: 10.0.1.111
      share: /mnt/styx/data/media/audiobooks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobooks-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: audiobookshelf-audiobooks-pv
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
  labels:
    app: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: metadata
              mountPath: /metadata
            - name: audiobooks
              mountPath: /audiobooks
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
        - name: audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  selector:
    app: audiobookshelf
  ports:
    - port: 80
      targetPort: 80
