apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newt-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/cnbrown04/homelab.git
    path: sisyphus/workloads/newt
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: newt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
