apiVersion: v1
kind: Secret
metadata:
    name: pocketid-secret
    namespace: pocketid
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:OWQI1Rzg2g3BgTPadhcKRcARbSTBSCXzLvQvnNn7G8lN9D6YIyj4JrZGTp4=,iv:xLaR1/cvl+0J/K6wDgPEvID4W1nDBy1Myo5ImShhM4g=,tag:aDw8nM98nxnYbXLr+FZ1Ww==,type:str]
    DB_CONNECTION_STRING: ENC[AES256_GCM,data:wPHp1lCm2EP7j7Hv6DFLLXlTFMC9vQ+mgRp+hdrEhy7W5MTflkk6wdKyPZNaZRHugJsySTbQVg5LLeO7LHlmH5H5uezkrMYUf6GWpMS+6ZrLjzeUq/Xy7ZJCfbypkyarN4LCOhsermgv89rdHuwE6uaHPlbiYhG67YVdwZavjkvR6XPLhqw7ke139koVrEJBZCwdDRhHjXEUVOz8cgFMZn1bYiqHHM0=,iv:NY0h6q/Lsk6v55EoeMrga+ZiyaXe94rcZP12USGbe/Q=,tag:MNhsSsHPgQMJwyXsAv6ocg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaGNDam50UmdRMHh1THlj
            WDNpTWMrc2kxZFl5SmkrOHNOTzMwUTI0aXdFCi9sTmZwVDA0SDJMZmV3Nzc0bVoz
            WXEvUkVxckptcTZnOHBLbnJNNFJ0ck0KLS0tIGNBMDlCMWpMRjZ3UXVKelNtL1d6
            Sys2OG1SMndzbllMd2FLQVdNN0x5clUKe8sdRbKL9E4B4N/2oFOMnui4WndqNul4
            6aqGRYMznyY2pYXwtnmPoxHCgmN07h66MhWFgpVPY27s9NJG9SrTxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ygm9sy4ww2l95wwpta72g9se7lev3mqp9d898zxzs9a36yx9gsmqsvl3t3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T23:31:59Z"
    mac: ENC[AES256_GCM,data:0fXaN1z3RBKMpCtT/Ox1Dg7R88q1VFsNQJvHA6iuIofZufq6jzBfPI51LL3yK9LZQh/lcWFQ25gjRCmiJfEEtVvedCXMROAQLpFATDsBIGYQ1e9zJgh25voOvRX+54FH5R7wZoNqH/P5ErMESqVHsRoUYphfvT9zJsf82H4HxfA=,iv:heHgom2OsI13OxUVCL6PZCOsx2ANljtMLFhwOPoyi2g=,tag:WPJbdqwQo/8nvQ9u3iRgew==,type:str]
    version: 3.13.2
